### ISSUE TITLE
nelze vybrat várku při objednávce piva

### ISSUE THREAD

**Issue by lahvy02** [Divocaak/garage-brewery#51]
Nevím jestli je to tím že jsem v profilu administrace, ale když jsem chtěl vybrat várku při objednávce, tak mi nevyjela lišta, jako mi třeba vyjela když jsem zvolil kdo bude řešit objednávku.

**Comment by Divocaak** [comment]
u objednávek jdou vybrat jenom ty várky, které mají status "k prodeji," jiné se nezobrazují. nechceme totiž, aby nám naskákalo x objednávek na várku, která může dokvasit špatně. až várka dokvasí a shodneme se, že jí můžeme prodávat, změníme její stav na "k prodeji," uživatelům rozešleme mail a oni ji budou moct vybrat v objednávce.

issue zavírám
